version: '3.8'
services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tournament_net

  kafka:
    image: bitnamilegacy/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - tournament_net

  kafka-worker:
    build:
      context: ./  
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: unless-stopped
    networks:
      - tournament_net

networks:
  tournament_net:
    external: true
